# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Max Fronek
email: mf@maxfronek.com
description: |
  I’ve been in love with design my entire life. Finding the perfect way to present information and solving problems creatively is a passion of mine.
  
  I work with various clients to achieve their short- and long-term needs focusing mainly on: product branding, product and packaging development, marketing, and corporate identity.
  
  Let’s chat about how we can elevate your brand together.
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
photourl: "http://localhost:4000/" # for image resources
twitter_username: classymax
github_username:  maxfronek
instagram_username: classymax
behance_username: maxfronek
dribbble_username: _mf
linkedin_username: maxfronek
behance_username: _mf

# Build settings
environment: development
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
img_sizes:
  icon:    
  tiny: 
  small: 
  medium: 
  grande:
  1k: 
  2k:  
defaults:
-
 scope:
   path: "" # an empty string here means all files in the project
   type: "posts" # previously `post` in Jekyll 2.2.
 values:
   layout: "default"
   is_post: true  
-
 scope:
   path: "" # an empty string here means all files in the project
   type: "pages" # previously `post` in Jekyll 2.2.
 values:
   layout: "default"
   is_page: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
