# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Max Fronek
email: mf@maxfronek.com
description: >- # this means to ignore newlines until "baseurl:"
  Los Angeles-based graphic / web designer and photographer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mf.design" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: classymax
github_username:  maxfronek
instagram_username: classymax
behance_username: maxfronek
dribbble_username: _mf
linkedin_username: maxfronek
behance_username: _mf

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-responsive-image
responsive_image:
  template: _includes/srcset.html
  sizes:
  - width: 480  # [Required] How wide the resized image will be.
    quality: 60 # [Optional] Overrides default_quality for this size.
  - width: 600
  - width: 1000
    quality: 80
  - width: 2000
    quality: 80    
defaults:
-
 scope:
   path: "" # an empty string here means all files in the project
   type: "posts" # previously `post` in Jekyll 2.2.
 values:
   layout: "default"
   is_post: true  
-
 scope:
   path: "" # an empty string here means all files in the project
   type: "pages" # previously `post` in Jekyll 2.2.
 values:
   layout: "default"
   is_page: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
